version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: intuitivecare
      POSTGRES_DB: agencias
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./assets:/assets
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/app/Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
      - ./assets:/assets
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "8080:80"
    restart: always

volumes:
  postgres_data: