version: "3.8"
services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: intuitivecare
      POSTGRES_DB: agencias
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/dockerfile
    container_name: backend_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:intuitivecare@db:5432/agencias
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data: